name: Build and Publish Ansible WinRM KRB5 image
 
on:
  push:
    paths:
    - 'dockerfiles/ansible-winrm-krb5/**'
    - '!dockerfiles/ansible-winrm-krb5/README.md'  

env:
  _GH_BASE_URI: https://github.com/
  _ANSIBLE_VERSION: 2.9.10
  _BASE_IMAGE_VERSION: 3.12.0
  _BASE_IMAGE: alpine
  _IMAGE_VARIANT: winrm-krb5
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Publish to Docker Repository
        env:
          _IMAGE_LONG_VERSION: ${{ env._ANSIBLE_VERSION }}-${{ env._IMAGE_VARIANT }}-${{ env._BASE_IMAGE }}${{ env._BASE_IMAGE_VERSION }}
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          context: dockerfiles/ansible-winrm-krb5
          buildargs: BASE_IMAGE_VERSION=${{ env._BASE_IMAGE_VERSION }}, ANSIBLE_VERSION=${{ env._ANSIBLE_VERSION }}, VCS_URL=${{ env._GH_BASE_URI }}${{ env.GITHUB_REPOSITORY }}, VCS_REF=${{ env.GITHUB_SHA }}, IMAGE_LONG_VERSION=${{ env._IMAGE_LONG_VERSION }}
          name: ${{ secrets.DOCKERHUB_REPO }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}
          tags: ${{ env._ANSIBLE_VERSION }}-${{ env._IMAGE_VARIANT }}-${{ env._BASE_IMAGE }}${{ env._BASE_IMAGE_VERSION }}, ${{ env._ANSIBLE_VERSION }}-${{ env._IMAGE_VARIANT }}, ${{ env._IMAGE_VARIANT }}
