name: Build and Publish Ansible PSRP KRB5 image
 
on:
  push:
    paths:
    - 'dockerfiles/ansible-psrp-krb5/**'
    - '!dockerfiles/ansible-psrp-krb5/README.md'  
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      _GH_BASE_URI: https://github.com/
      _ANSIBLE_VERSION: 2.9.1
      _BASE_IMAGE_VERSION: 3.11.3
      _BASE_IMAGE: alpine
      _IMAGE_VARIANT: psrp-krb5
      
    steps:
      - uses: actions/checkout@v1
      - name: Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          context: dockerfiles/ansible-psrp-krb5
          buildargs: BASE_IMAGE_VERSION=${{ _BASE_IMAGE_VERSION }}, ANSIBLE_VERSION=${{ _ANSIBLE_VERSION }}, VCS_URL=${{ GH_BASE_URI }}${{ GITHUB_REPOSITORY }}, VCS_REF=${{ GITHUB_SHA }}
          name: ${{ secrets.DOCKERHUB_REPO }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}
          tags: ${{ _ANSIBLE_VERSION }}-${{ _IMAGE_VARIANT }}-${{ _BASE_IMAGE }}${{ _BASE_IMAGE_VERSION }}, ${{ _ANSIBLE_VERSION }}-${{ _IMAGE_VARIANT }}, ${{ _IMAGE_VARIANT }}